project_id = "nkmjkjgkpbzgsbvzdetz"

[functions.edit-user]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.analyze-personality]
verify_jwt = false

[functions.analyze-human-design]
verify_jwt = false

[functions.recalculate-results]
verify_jwt = false

[functions.analyze-integrated]
verify_jwt = false
